services:
  db:
    container_name: mysql
    build:
      context: mysql
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    env_file:
      - mysql/.env
    # DBのコンテナのヘルスチェックを行う
    # mysqladmin(MySQLサーバーの管理を行うクライアントを使ってDBコンテナ自身(127.0.0.1)にpingを送ってヘルスチェックを行う
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は30秒
      start_period: 30s
  django_app:
    container_name: django_app
    build:
      context: djangopj
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: djangopj
        target: /djangopj
      - type: volume
        source: static
        target: /static
    expose:
      - 8001
    ports:
      - 8999:8999
    depends_on:
      db:
        condition: service_healthy
  static_app:
    container_name: static_app
    build:
      context: static_app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: static_app/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: static_app/www
        target: /usr/local/apache2/htdocs
    expose:
      - 8001
    depends_on:
      - django_app
  web:
    container_name: web
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: static
        target: /static
    ports:
      - "80:80"
    depends_on:
      - static_app
volumes:
  db_data:
  static:
